version: "3"
services:
  correction:
    image: "docker.pkg.github.com/alercebroker/correction_step/correction_step:0.0.1"
    restart: "always"
    environment:
      - DB_HOST=
      - DB_USER=
      - DB_PASSWORD=
      - DB_PORT=
      - DB_NAME=
      - CONSUMER_TOPICS=
      - CONSUMER_SERVER=
      - CONSUMER_GROUP_ID=
      - AVRO_PATH=
      - PRODUCER_TOPIC=
      - PRODUCER_SERVER=
      - ES_PREFIX=
      - ES_NETWORK_HOST=
      - ES_NETWORK_PORT=
      - LOGGING_DEBUG=False
      - N_PROCESS=
      - METRICS_HOST=
      - METRICS_TOPIC=
