[project]
name = "correction"
dynamic = ["version"]
description = "Correction library for ALeRCE pipeline."
authors = [
    {email = "contact@alerce.online"},
    {name = "ALeRCE Team"}
]
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "numpy~=1.24.2",
    "pandas~=1.5.3",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-docker",
    "coverage",
    "black",
]
pipeline = [
    "fastavro~=1.4.12",
    "prometheus-client~=0.16.0",
    "apf_base~=2.1.5",
]

[tool.setuptools.dynamic]
version = {attr = "correction.__version__"}

#[project.scripts]
#dbp = "db_plugins.cli.manage:cli"

[project.urls]
repository = "https://github.com/alercebroker/db-plugins"
